modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/LocalizedMC/SubLangView/issues"
license = "LGPL-3.0"

[[mods]]
modId = "sublangview"
version = "${version}"
displayName = "SubLangView"
displayURL = "https://github.com/LocalizedMC/SubLangView"
authors = "TexTrue, Wulian233"
description = '''

'''
#logoFile = ""

[[dependencies.sublangview]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "sublangview.mixins.json"
